apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/lalanura/udagram-frontend:v1
        ports:
        - containerPort: 80
        resources:
          limits:
             cpu: 250m
             memory: 64Mi
          requests:
             cpu: 200m
             